# Generated by Django 5.2.6 on 2025-09-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
